apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: gabriel1304/flask-app:latest
          env:
            - name: WELCOME_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: welcome-message
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: api-key
          volumeMounts:
            - name: flask-storage
              mountPath: /app/data
      volumes:
        - name: flask-storage
          persistentVolumeClaim:
            claimName: flask-pvc
